refactor: enhance logging format in init script with color coding for better visibility

diff --git a/docker/init_scripts/init b/docker/init_scripts/init
--- a/docker/init_scripts/init
+++ b/docker/init_scripts/init
@@ -21,23 +21,32 @@ INIT_DEBUG="${INIT_DEBUG:="false"}"
 # (since backend is almost 100% async this won't block anything)
 DEFAULT_WEB_CONCURRENCY=1
 
+# logger colors
+RED='\033[0;31m'
+LIGHTMAGENTA='\033[0;95m'
+GREEN='\033[0;32m'
+YELLOW='\033[0;33m'
+BLUE='\033[0;36m'
+CYAN='\033[0;36m'
+RESET='\033[0;00m'
+
 # print debug log output if enabled
 debug_log() {
 	if [[ ${INIT_DEBUG} == "true" ]]; then
-		echo "DEBUG:    [RomM][init][$(date +"%Y-%m-%d %T")]" "${@}" || true
+		echo -e "${LIGHTMAGENTA}DEBUG:    ${BLUE}[RomM]${LIGHTMAGENTA}[init]${CYAN}[$(date +"%Y-%m-%d %T")]${RESET}" "${@}" || true
 	fi
 }
 
 info_log() {
-	echo "INFO:     [RomM][init][$(date +"%Y-%m-%d %T")]" "${@}" || true
+	echo -e "${GREEN}INFO:     ${BLUE}[RomM]${LIGHTMAGENTA}[init]${CYAN}[$(date +"%Y-%m-%d %T")]${RESET}" "${@}" || true
 }
 
 warn_log() {
-	echo "WARNING:  [RomM][init][$(date +"%Y-%m-%d %T")]" "${@}" || true
+	echo -e "${YELLOW}WARNING:  ${BLUE}[RomM]${LIGHTMAGENTA}[init]${CYAN}[$(date +"%Y-%m-%d %T")]${RESET}" "${@}" || true
 }
 
 error_log() {
-	echo "ERROR:    [RomM][init][$(date +"%Y-%m-%d %T")]" "${@}" || true
+	echo -e "${RED}ERROR:    ${BLUE}[RomM]${LIGHTMAGENTA}[init]${CYAN}[$(date +"%Y-%m-%d %T")]${RESET}" "${@}" || true
 	exit 1
 }
 
